# Generated by Django 2.0b1 on 2017-11-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0002_auto_20171111_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trees',
            name='Answer10',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer6',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer7',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer8',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer9',
        ),
    ]
