# Generated by Django 2.0b1 on 2017-11-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0006_remove_trees_answer13'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trees',
            name='Answer10',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer11',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer12',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer7',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer8',
        ),
        migrations.RemoveField(
            model_name='trees',
            name='Answer9',
        ),
    ]
