# Generated by Django 2.0b1 on 2017-11-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0008_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='ImgData',
            field=models.TextField(max_length=31341, verbose_name='ImgData'),
        ),
    ]
