# Generated by Django 2.0b1 on 2017-11-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0009_auto_20171121_2026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imgs',
        ),
    ]
