# Generated by Django 2.0rc1 on 2017-11-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0010_delete_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseID', models.TextField(max_length=100, verbose_name='HOUSEID')),
                ('confirmDATE', models.DateTimeField(auto_now=True, verbose_name='CONFIRMDATE')),
                ('Answer1', models.IntegerField(null=True, verbose_name='Answer1')),
                ('Answer2', models.IntegerField(null=True, verbose_name='Answer2')),
                ('Answer3', models.IntegerField(null=True, verbose_name='Answer3')),
                ('Answer4', models.IntegerField(null=True, verbose_name='Answer4')),
                ('Answer5', models.IntegerField(null=True, verbose_name='Answer5')),
                ('Answer6', models.IntegerField(null=True, verbose_name='Answer6')),
            ],
        ),
    ]
